name: Run Discord Bot Daily

on:
  schedule:
    - cron: '54 07 * * *'  # Runs at 17:30 UTC every day

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install discord.py requests pytz apscheduler
    - name: Run script
      run: python bot.py
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

